import { Inter } from "next/font/google";
import "../stylesheet/globals.css";
import Providers from "@/redux/provider";
import NavBar from "@/components/navBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
